### PR TITLE
Add options to refresh script

### PR DESCRIPTION
**Pull request by dcw312**
Addresses https://github.com/cqframework/ecqm-content-r4-2021/issues/16

### CODE REVIEW

**Comment by rob-reynolds** [comment]
@dcw312 Thanks, David.

There is a requirement to keep the scripts for different OSs in sync.  IOW, we also need to update the .bat.  

I can work on that this weekend.

**Comment by rob-reynolds** [comment]
I'll just use this same branch/PR if you don't mind.

**Comment by dcw312** [comment]
> I'll just use this same branch/PR if you don't mind.

@rob-reynolds Perfect. I added you as a collaborator on my fork. Feel free to do their or here. I didn't update the Alphora URL. If that's a real option, please update the sh file too. I maintained backward compatibility.

**Review by rob-reynolds — APPROVED** [review]
Runs locally

**Comment by rob-reynolds** [comment]
Note, .bat version is being created on a separate branch: https://github.com/cqframework/ecqm-content-r4-2021/pull/20.

**Review by brynrhodes — APPROVED** [review]

**Pull request merged**
